config/routes.rb
Website::Application.routes.draw do
  root to: "pages#index"
  resources :experiences, only: [:index, :show], param: :name
  resources :projects, only: [:index, :show], param: :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  caches_page :index
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  caches_page :index
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  caches_page :index
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiences/_enova.haml
.work
  .enova
    .work-experience
      =image_tag 'enova.jpg'
      .work-details
        %h2 Software Engineering Intern
        %h3 Chicago, IL
        %h3 August 2012 - September 2013
      %ul.experience-stories
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Streamlined manual data-entry in call center using a Redis-backed queue in a Ruby on Rails application to automate payment scheduling with approximately $200K ROI
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Improved customer representative performance by revamping search workflow in production using internal API for SQL querying with approximately $500K ROI
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Designed multiple functional, unit, integration, and end-to-end tests using RSpec and Cucumber to ensure the business requirements were met in four Rails projects
      %ul.experience-stories
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Implemented Riak data storage as a means to lookup email metadata through MapReduce queries, secondary indices, and search as a proof of concept
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Designed and implemented an application to handle incoming HTTP requests and to create and update a poker game-state for two hackathons for college students
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Explored open source and paid proprietary solutions for speech recognition to translate call data into text for quality assurance and fraud analytics

app/views/experiences/_opower.haml
.work
  .opower
    .work-experience
      %h1.brand
      .work-details
        %h2 2014 KPCB Engineering Fellow
        %h3 San Francisco, CA
        %h3 June 2014 - September 2014
      %ul.experience-stories
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Adapted Rails application to handle new location-based functionality to communicate with iOS and Android apps for thousands of customers using smart thermostats
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Collaborated with team leaders to develop new user interface in AngularJS application to improve customer experience in controlling smart thermostats
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Upgraded legacy Customer Service Portal to provide customer status by modifying SQL view, creating new server endpoints, and updating AngularJS application
    =image_tag 'automatic_away_screenshot.png', class: 'opower-screenshot'

app/views/experiences/_starterleague.haml
.work
  .starterleague
    .work-experience
      %h1.brand
      .work-details
        %h2 Summer 2012 Dev Student
        %h3 Merchandise Mart, Chicago, IL
        %h3 June 2012 - August 2012
      %ul.experience-stories
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Attended a 10-week program in 1871, Chicago's entrepreneurial hub for digital startups, where I learned Ruby on Rails, HTML, CSS, and Javascript along with 30 other students
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p
              Worked as lead developer on a team to build
              %span#happyhealth HappyHealth
              for the Demo Day presentation at the end of the curriculum and presented to over 100 attendees
    =image_tag 'starter-league-art.jpg', class: 'stl-image'

app/views/experiences/index.haml
#experience
  %h1.heading Experience
  %p.viewpoint I owe a lot to the mentors and friends at these companies who have guided my development as an engineer and helped me reach where I am today.
  #details
    .work-images
      .image-block=link_to (image_tag 'starterleague-logo.png'), experience_path(name: 'starterleague'), remote: true
      .image-block=link_to (image_tag 'enova-logo.png'), experience_path(name: 'enova'), remote: true
      .image-block=link_to (image_tag 'opower.png'), experience_path(name: 'opower'), remote: true

app/views/experiences/show.js.erb
$('.work').remove()
$('#experience').append("<%= j(render(params[:name])) %>")
$(".<%= params[:name] %>").fadeIn(400)
$('html, body').animate({scrollTop:$(document).height()}, 'slow');

app/views/layouts/_header.haml
.header
  .container
    %ul
      %li
        =link_to "HOME", "/", class: 'nav-link'
      %li
        =link_to "EXPERIENCE", "/experiences", class: 'nav-link'
      %li
        =link_to "PROJECTS", "/projects", class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Shaan Sapra, Software Engineer, KPCB Fellow, Code Monkey</title>
		<%= favicon_link_tag "favicon.ico" %>
		<%= stylesheet_link_tag 'application', media: 'all' %>
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <meta property="og:description" content="I am a third-year student at the University of Chicago studying Computer Science and Economics.After taking the Ruby on Rails course at The Starter League in Chicago's 1871, I have grown to love the world of software development and programming. I am experienced in MVC architecture and web development and familiar with the staging, testing, and deploying cycles of software development. I am always looking to solve meaningful challenges with innovative solutions and continually improve my technical skills." />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
		<meta name="viewport" content="width=device-width, user-scalable=no">
    <meta content="black" name="apple-mobile-web-app-status-bar-style" />
    <meta property="og:image" content="http://a4.res.cloudinary.com/hvqqwrowv/image/asset/profile-0bc9bf9a811785de1720755884199d11.jpg" />
    <meta property="og:title" content="Shaan Sapra" />
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div class="main">
			<%= render "layouts/header" %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/_home.haml
.content.home-container
	#home
		=image_tag "profile.jpg", :class => "background-image"
		.home
			.home-details
				%h1 Hi, I'm Shaan Sapra
				%p I'm a software developer in Chicago.
				%p
					Check out more about my
					=link_to 'experience', '/experience', class: 'nav-link', remote: true
					and past
					=link_to 'projects', '/projects', class: 'nav-link', remote: true
				%p Reach out to me:
				.contact-container
					.left-side
						%ul.icons
							%li
								%i.fa.fa-envelope
							%li
								%i.fa.fa-github-square
							%li
								%i.fa.fa-linkedin-square
						%ul.contact
							%li= link_to "<p>shaanfire@gmail.com</p>".html_safe, 'mailto:shaanfire@gmail.com'
							%li= link_to "<p>Github</p>".html_safe, 'https://github.com/ssapra', target: '_'
							%li= link_to "<p>LinkedIn</p>".html_safe, 'http://www.linkedin.com/in/shaansapra', target: '_'

app/views/pages/_opower.haml
.work
  .opower
    .work-experience
      %h1.brand Opower
      .work-details
        %h2 2014 KPCB Engineering Fellow
        %h3 San Francisco, CA
        %h3 June 2014 - September 2014
      %ul.experience-stories
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Adapted Rails application to handle new location-based functionality to communicate with iOS and Android apps for thousands of customers using smart thermostats
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Collaborated with team leaders to develop new user interface in AngularJS application to improve customer experience in controlling smart thermostats
        %li
          .story
            %i.fa.fa-arrow-circle-o-right.icon
            %p Upgraded legacy Customer Service Portal to provide customer status by modifying SQL view, creating new server endpoints, and updating AngularJS application
    =image_tag 'automatic_away_screenshot.png', class: 'opower-screenshot'

app/views/pages/index.haml
.content.home-container
	#home
		=image_tag "profile.jpg", :class => "background-image"
		.home
			.home-details
				%h1 Hi, I'm Shaan Sapra
				%p I'm a software developer in Chicago.
				%p
					Check out more about my
					=link_to 'experience', '/experiences', class: 'nav-link'
					and past
					=link_to 'projects', '/projects', class: 'nav-link'
				%p Reach out to me:
				.contact-container
					.left-side
						%ul.icons
							%li
								%i.fa.fa-envelope
							%li
								%i.fa.fa-github-square
							%li
								%i.fa.fa-linkedin-square
						%ul.contact
							%li= link_to "<p>shaanfire@gmail.com</p>".html_safe, 'mailto:shaanfire@gmail.com'
							%li= link_to "<p>Github</p>".html_safe, 'https://github.com/ssapra', target: '_'
							%li= link_to "<p>LinkedIn</p>".html_safe, 'http://www.linkedin.com/in/shaansapra', target: '_'

app/views/pages/uevents.js.erb
$('.project-entry').remove()
$('#experience').append("<%= j(render 'uevents') %>")
$('html, body').animate({scrollTop:$(document).height()}, 'slow');

app/views/projects/_edge.haml
.project-entry
  .details
    %p HappyHealth is an online patient registration tool that makes it easy for patients to store their basic personal, medical and insurance information to spare you the hassle at the doctor's office.
  .project-image-container
    =image_tag 'happyhealth.png', class: 'project-image'

app/views/projects/_happyhealth.haml
.project-entry
  .details
    %p HappyHealth is an online patient registration tool that makes it easy for patients to store their basic personal, medical and insurance information to spare you the hassle at the doctor's office.
  .project-image-container
    =image_tag 'happyhealth.png', class: 'project-image'

app/views/projects/_nolimitcodeem.haml
.project-entry
  .details
    %p No Limit Code 'Em is variation of the poker game No Limit Hold 'Em, designed as a hackathon in which students compete against each other to build a poker bot and compete against each other at our tables.
  .project-image-container
    =image_tag 'enova.png', class: 'project-image'

app/views/projects/_reliefwatch.haml
.project-entry
  .details
    %p Project SAM (SMS Accounting Management) is a platform that allows healthcare systems in developing countries to effectively integrate their inventory records and efficiently manage supply shipments through basic feature-phones.
  .project-image-container
    =image_tag 'projectsam.png', class: 'project-image'

app/views/projects/_uevents.haml
.project-entry
  .details
    %p UEvents is an application that taps into the UChicago facebook community to offer a comprehensive, centralized list of all public events for UChicago students.
  .project-image-container
    =image_tag 'uevents.png', class: 'project-image'

app/views/projects/index.haml
#experience
  %h1.heading Projects
  %p.viewpoint While I was at the University of Chicago, I had the opportunity to work on several projects with friends and colleagues. Some have spun off into fully-fledged startups and some have been put to rest until a later day. Check them out!
  #details
    .work-images
      .image-block=link_to (image_tag 'phoenixpitch-logo.png'), project_path(name: 'phoenixpitch'), remote: true
      .image-block=link_to (image_tag 'edge.png'), project_path(name: 'edge'), remote: true
      .image-block=link_to (image_tag 'uevents-logo.png'), project_path(name: 'uevents'), remote: true
    .work-images
      .image-block=link_to (image_tag 'reliefwatch.png'), project_path(name: 'reliefwatch'), remote: true
      .image-block=link_to (image_tag 'enova-logo.png'), project_path(name: 'nolimitcodeem'), remote: true
      .image-block=link_to (image_tag 'happyhealth-logo.jpg'), project_path(name: 'happyhealth'), remote: true

app/views/projects/show.js.erb
$('.project-entry').remove()
$('#experience').append("<%= j(render(params[:name])) %>")
$('html, body').animate({scrollTop:$(document).height()}, 'slow');